services:
  neo4j:
    image: neo4j:5.3
    container_name: neo4j
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
    ports:
      - "7474:7474"   # Neo4j Browser
      - "7687:7687"   # Bolt protocol

  app:
    build: ./app
    environment:
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
    volumes:
      - ./app:/app
    command: python /app/main.py

  neodash:
    image: neo4jlabs/neodash:latest
    container_name: neodash
    platform: linux/amd64
    ports:
      - "5005:5005"
    environment:
      - NEO4J_URL=bolt://neo4j:7687
      - NEO4J_USERNAME=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
