services:
  neo4j:
    image: neo4j:5.3
    container_name: neo4j
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
    ports:
      - "7474:7474"   # Neo4j Browser
      - "7687:7687"   # Bolt protocol
    healthcheck:
      test: ["CMD", "curl", "-sS", "http://neo4j:7474"]
      interval: 10s
      retries: 10
      start_period: 40s
      timeout: 10s

  app:
    build: ./app
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
    volumes:
      - ./app:/app
    command: python /app/main.py

